language: python
python:
 - "2.7"
 - "3.2"
 - "3.3"
 - "3.4"
 - "3.5"
 - "pypy"
cache: pip
install:
 - pip install codeclimate-test-reporter coverage
 - pip install -r requirements.txt
script:
 - if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then nosetests; else nosetests --with-coverage; fi
after_success:
  - if [[ $TRAVIS_PYTHON_VERSION != '3.2' ]]; then CODECLIMATE_REPO_TOKEN=c9bb4362e87117de1c8e4ed83afad7b4068193d726e324a6280115c6dcde882b codeclimate-test-reporter; fi
