language: python
python:
 - "2.7"
 - "3.4"
 - "pypy"
cache: pip
install:
 - pip install coverage
 - pip install codeclimate-test-reporter
 - pip install -r requirements.txt
script:
 - nosetests --with-coverage
after_success:
  - CODECLIMATE_REPO_TOKEN=c9bb4362e87117de1c8e4ed83afad7b4068193d726e324a6280115c6dcde882b codeclimate-test-reporter
